site_name: VU LSC PhD Student Guide
site_url: https://justinaskav.github.io/phd-guide/ 
repo_url: https://github.com/justinaskav/phd-guide
repo_name: lsc/phd-guide
edit_uri: edit/main/docs/
theme:
  # logo: 
  # favicon:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: 
    text: Nunito Sans
  features:
    - content.action.view
    - content.action.edit
    - footnotes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.expand
    # - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    # - navigation.tabs
    # - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight

markdown_extensions: 
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbrevations.md
  - toc:
      permalink: true
  
watch:
  - includes

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - privacy
  # - social
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: lt
          name: Lietuvių
          default: true
          site_name: VU GMC doktorantūros studentų gidas
          nav:
            - Pradžia: index.md
            - Studijos: 
              - Apie doktorantūros studijas: studies/about-phd.md
              - Doktorantūros studijų eiga: 
                - Planas: studies/phd-plan.md
                - Egzaminai: studies/exams.md
                - Bendrosios kompetencijos: studies/transferable-skills.md
                - Ataskaitos: studies/progress-reports.md
                - Disertacija ir studijų baigimas: studies/completion.md
              - Finansai: studies/finances.md
            - GMC struktūra: lsc-structure.md
            - Atstovavimas: student-representation.md
            - Kontaktai: contacts.md
            - Naudingos nuorodos: useful-links.md
            - DUK: faq.md
        - locale: en
          name: English
          site_name: Guide for Life Sciences Center PhD Students 
          nav:
            - Home: index.md
            - Studies: 
              - About: studies/about-phd.md
              - Course of PhD Studies: 
                - Plan: studies/phd-plan.md
                - Exams: studies/exams.md
                - Transferable Skills: studies/transferable-skills.md
                - Progress Reports: studies/progress-reports.md
                - Dissertation and study completion: studies/completion.md
              - Finances: studies/finances.md
            - LSC Structure: lsc-structure.md
            - Student Representation: student-representation.md
            - For International Students: for-international-students.md
            - Contacts: contacts.md
            - Useful Links: useful-links.md
            - FAQ: faq.md
  - git-revision-date-localized:
      enable_creation_date: true
