site_name: Guide for Life Sciences Center PhD Students 
# site_url: 
# repo_url:
# repo_name
theme:
  # logo: 
  # favicon:
  name: material
  palette:
    primary: custom
    accent: custom
  font: 
    text: Nunito Sans
  features:
    - content.action.view
    - content.action.edit
    - footnotes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    # - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.tabs
    # - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight

markdown_extensions: 
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbrevations.md
  - toc:
      permalink: true
  
watch:
  - includes

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - privacy
  # - social
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: lt
          name: Lietuvių
          default: true
        - locale: en
          name: English
          nav:
            - Intro: index.md
            - Studies: 
              - About: studies/about-phd.md
              - Course of PhD Studies: 
                - Plan: studies/phd-plan.md
                - Exams: studies/exams.md
                - Transferable Skills: studies/transferable-skills.md
                - Progress Reports: studies/progress-reports.md
                - Completion: studies/completion.md
              - Finances: studies/finances.md
            - LSC Structure: lsc-structure.md
            - Student Representation: student-representation.md
            - For International Students: for-international-students.md
            - Contacts: contacts.md
            - Useful Links: useful-links.md
            - FAQ: faq.md
